version: '3.8'

services:
  robotarm_core:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    network_mode: host
    privileged: true
    volumes:
      - .:/ros2_ws/src
      - /etc/localtime:/etc/localtime:ro
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && tail -f /dev/null"

  micro-ros-agent:
    image: microros/micro-ros-agent:humble
    network_mode: host
    privileged: true
    command: udp4 --port 8888
    restart: always